# The upstream version of FreeBSD we are pulling from.
VER=15.1-RELEASE

# The download URL for the source code.
SRC="http://ftp.freebsd.org/pub/FreeBSD/releases/amd64/${VER}/src.txz"

# checksum
SHA256="cf5762da53fd52e1eaf0f9ceee9bf58cbe314c821031d0d9ffa76823185a89e1"
